src/Entity/ClientApiUrl.php
<?php

namespace App\Entity;

use App\Repository\ClientApiUrlRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClientApiUrlRepository::class)
 */
class ClientApiUrl
{
    public function __construct()
    {
        $this->dateQueried = new \DateTime('1/1/1990');
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="guid")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $URLName;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="clientApiUrls")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $IpAddressList;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Notes;

        /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $queryFromIPaddress;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateQueried;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getURLName(): ?string
    {
        return $this->URLName;
    }

    public function setURLName(string $URLName): self
    {
        $this->URLName = $URLName;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getIpAddressList(): ?string
    {
        return $this->IpAddressList;
    }

    public function setIpAddressList(?string $IpAddressList): self
    {
        $this->IpAddressList = $IpAddressList;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->Notes;
    }

    public function setNotes(?string $Notes): self
    {
        $this->Notes = $Notes;

        return $this;
    }





    public function getQueryFromIPaddress(): ?string
    {
        return $this->queryFromIPaddress;
    }

    public function setQueryFromIPaddress(string $queryFromIPaddress): self
    {
        $this->queryFromIPaddress = $queryFromIPaddress;

        return $this;
    }

    public function getDateQueried(): ?\DateTimeInterface
    {
        return $this->dateQueried;
    }

    public function setDateQueried(\DateTimeInterface $dateQueried): self
    {
        $this->dateQueried = $dateQueried;

        return $this;
    }
}

src/Form/IPsType.php
<?php

namespace App\Form;

use App\Entity\IPList;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IPsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
	    $builder
		->add('listType', TextType::class,[
		    'label'  => 'List Name.',
		])
		->add('IPList',TextareaType::class,[
		    'label'  => 'IP List.',
		])
		->add('notes',TextareaType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => IPList::class,
        ]);
    }
}

templates/ips/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create IP!{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 ">
                <div class="card bg-light mb-3 mt-5" style="width: 800px">
                    <div class="card-body">
                        <div class="card-header mb-3">NEW API IP address for {{ client.getClientName }}</div>
                        {% if app.user != null %}
                            {{ form_start(form) }}
                            <div class="form_group">
                                <div class="col-md-12 mb-3">
                                    {{ form_row(form.URLName, {'attr': {'class': 'form-control'}}) }}
                                    {{ form_row(form.IpAddressList, {'attr': {'class': 'form-control'}}) }}
				                    {{ form_row(form.Notes, {'attr': {'class': 'form-control'}}) }}
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 c" style="margin-top:5px;">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-btn fa-user"></i> Create
                                    </button>
                                </div>
                            </div>
                            {{ form_end(form) }}

                            <div class="form_group col-md-12 mb-3">
                                <br>
                                <a class="btn btn-primary" href="{{ path('list_client_ips',{ 'client' :  client.id }) }}" role="button">Back</a>
                            </div>

                        {% endif %}
                        {% if app.user == null %}
                            <a href="{{ path('app_login') }}" class="btn btn-info">Please Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ips/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create IP!{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 ">
                <div class="card bg-light mb-3 mt-5" style="width: 800px">
                    <div class="card-body">

                        <div class="card-header mb-3"><h1>Edit IP list for {{ clientApiUrl.client.clientName }}</h1></div>
                        {% if app.user != null %}
                            {{ form_start(form) }}
                            <div class="form_group">
                                <div class="col-md-12 mb-3">
                                    {{ form_row(form.URLName, {'attr': {'class': 'form-control'}}) }}
                                    {{ form_row(form.IpAddressList, {'attr': {'class': 'form-control'}}) }}
                                    {{ form_row(form.Notes, {'attr': {'class': 'form-control'}}) }}
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 " style="margin-top:5px;">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-btn fa-user"></i>Update
                                    </button>


                                </div>
                            </div>
                            {{ form_end(form) }}
			            <div class="form_group col-md-12 mb-3">
                            <br>
                            <a class="btn btn-primary" href="{{ path('list_client_ips',{ 'client' :  clientApiUrl.client.id }) }}" role="button">Back</a>
                        </div>
                        {% endif %}
                        {% if app.user == null %}
                            <a href="{{ path('app_login') }}" class="btn btn-info">Please Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ips/listIPs.html.twig
{% extends 'base.html.twig' %}

{%  block stylesheets %}
    <style>
        input[type=text] {
            width: 100%;
            padding: 1px 1px;
            margin: 8px 0;
            box-sizing: border-box;
            font-size: 12px;
        }
    </style>
{%  endblock %}


{% block title %}Client IP List{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card bg-light mb-3 mt-5" >
                    <div class="card-body">

			{# pass an array argument to get the messages of those types  #}
                        {% for label, messages in app.flashes([]) %}
                            {% for message in messages %}
                                <div class="alert alert-{{ label }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endfor %}                        

			{% if app.user != null %}
                            <div class="card-header">
                                <h1>Defined IP lists for {{ client.clientName }}</h1>
                            </div>
                            <table class="table">
                                <tr>
                                    <th>Name.</th>
                                    <th>IP.</th>
                                    <th>Idle</th>
                                    <th>Edit.</th>
                                    <th>Delete.</th>
                                    <th>OPNsense URL.</th>
                                    <th>Test</th>
                                </tr>

                                {%  for ips in client.clientApiUrls %}


                                    <tr>
                                        <td>{{ ips.uRLName }} </td>
                                        <td>{{ ips.ipAddressList|nl2br }}</td>

                                        {% set difference = date().diff(ips.dateQueried | default  ) %}
                                        {% if difference.days < 2 %}
                                            <td><span class="glyphicon glyphicon-ok " style="color: green"></span> </td>
                                        {% else %}
                                            <td><span class="glyphicon glyphicon-remove " style="color: red"></span></td>
                                        {% endif %}

                                        <td><a href=" {{ url('edit_client_ip', { 'clientApiUrl': ips.id }) }}">Edit</a></td>
                                        <td><a href=" {{ url('delete_client_ip', { 'clientApiUrl': ips.id }) }}">Delete</a></td>
                                        <td><input type="text" style = "font-size: 12px; " size = '85' value="{{ thisHost }}/api/{{ ips.id }}" id="myInput{{ loop.index}} " ></td>
{#                                        <td><a class="btn btn-primary" href="http://localhost/api/{{ ips.id }}" target="_blank">Test</a></td>#}
                                        <td><a class="btn btn-primary" href="/api/{{ ips.id }}" target="_blank">Test</a></td>
                                    </tr>

                                {%  endfor %}
                            </table>
                                <h4>Global</h4>
                            <table class="table">
                                <tr>
                                    <th>Name.</th>
                                    <th>IP.</th>
                                    <th>Idle</th>
                                    <th>Edit.</th>
                                    <th>Delete.</th>
                                    <th>OPNsense URL.</th>
                                    <th>Test</th>
                                </tr>
                                {%  if global is not null and global is not empty %}
                                    {%  for ips in global.clientApiUrls %}

                                        <tr>
                                            <td>{{ ips.uRLName }} </td>
                                            <td>{{ ips.ipAddressList|nl2br }}</td>

                                            {% set difference = date().diff(ips.dateQueried | default  ) %}
                                            {% if difference.days < 2 %}
                                                <td><span class="glyphicon glyphicon-ok " style="color: green"></span> </td>
                                            {% else %}
                                                <td><span class="glyphicon glyphicon-remove " style="color: red"></span></td>
                                            {% endif %}

                                            <td><a href=" {{ url('edit_client_ip', { 'clientApiUrl': ips.id }) }}">Edit</a></td>
                                            <td><a href=" {{ url('delete_client_ip', { 'clientApiUrl': ips.id }) }}">Delete</a></td>
                                            <td><input type="text" style = "font-size: 12px; " size = '85' value="{{ thisHost }}/api/{{ ips.id }}" id="myInput{{ loop.index}} " ></td>
                                            {#                                        <td><a class="btn btn-primary" href="http://localhost/api/{{ ips.id }}" target="_blank">Test</a></td>#}
                                            <td><a class="btn btn-primary" href="/api/{{ ips.id }}" target="_blank">Test</a></td>
                                        </tr>

                                    {%  endfor %}
                                {% endif %}

                            </table>

                            <div class="form_group col-md-12 mb-3">
                                <a class="btn btn-primary" href="{{ path('create_client_ip', { 'client': client.id}) }}" role="button">Create New</a>
                            </div>

                            <div class="form_group col-md-12 mb-3">
                                <a class="btn btn-primary" href="{{ path('list_clients') }}" role="button">Back</a>
                            </div>
                        {% endif %}

                        {% if app.user == null %}
                            <a href="{{ path('app_login') }}" class="btn btn-info">Please Login</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}